stages:
  train_baseline:
    cmd: python -m creditrisk.pipelines.train_baseline --config configs/baseline.yaml
    deps:
      - configs/baseline.yaml
      - src/creditrisk/config.py
      - src/creditrisk/data/datasets.py
      - src/creditrisk/features/feature_store.py
      - src/creditrisk/features/preprocess.py
      - src/creditrisk/models/baseline.py
      - src/creditrisk/pipelines/train_baseline.py
      - data/raw/application_train.csv
      - data/raw/bureau.csv
      - data/raw/bureau_balance.csv
      - data/raw/previous_application.csv
      - data/raw/installments_payments.csv
      - data/raw/credit_card_balance.csv
      - data/raw/POS_CASH_balance.csv
    params:
      - configs/baseline.yaml:
          - data.raw_path
          - data.target_column
          - training.test_size
          - training.random_state
          - model.type
    outs:
      - models/baseline_model.joblib
      - reports/metrics.json
      - reports/evaluation
